-- MySQL Script generated by MySQL Workbench
-- Fri Jun  9 11:07:57 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema dbApp
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema dbApp
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dbApp` DEFAULT CHARACTER SET utf8 ;
USE `dbApp` ;

-- -----------------------------------------------------
-- Table `dbApp`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbApp`.`usuario` (
  `id` INT NOT NULL,
  `nombreUser` VARCHAR(50) NULL,
  `correo` VARCHAR(50) NULL,
  `pass` VARCHAR(100) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbApp`.`portafolio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbApp`.`portafolio` (
  `id` INT NOT NULL,
  `titulo` VARCHAR(45) NULL,
  `url` VARCHAR(45) NULL,
  `tagurl` VARCHAR(45) NULL,
  `contenido` VARCHAR(100) NULL,
  `proyecto` VARCHAR(100) NULL,
  `cliente` VARCHAR(45) NULL,
  `impresion` VARCHAR(45) NULL,
  `portafoliocol` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `usuario_id`
    FOREIGN KEY (`id`)
    REFERENCES `dbApp`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbApp`.`imagenes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbApp`.`imagenes` (
  `id` INT NOT NULL,
  `ruta` VARCHAR(50) NULL,
  `nombreImg` VARCHAR(50) NULL,
  `base64` VARCHAR(200) NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `id_portafolio`
    FOREIGN KEY (`id`)
    REFERENCES `dbApp`.`portafolio` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
